language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t kmensah/docker-react -f Dockerfile.dev .

    script:
        - docker run -e CI=true Win 10/docker-react npm run test