sudo: required
services: 
    - docker

before_install:
    - docker build -t kmensah/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kmensah/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region : "eu-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-199722415292"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY